[package]
name = "graph-rdfa-processor"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Graph RDFa processor"
authors = ["Nordine Bittich"]
repository = "https://github.com/nbittich/graph-rdfa-processor"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
itertools = "0.11.0"
lazy_static = "1.4.0"
scraper = "0.18.1"
url = "2.4.1"
uuid = { version = "1.5.0", features = ["v4"] }
regex = "1.10.2"
ego-tree = "0.6.2"


[dev-dependencies]
# some tests must run sequentially. 
# if library is broken, alternative is: cargo test -- --test-threads 1
serial_test = "2.0.0"
test-case = "3.2.1"
env_logger = "0.10.0"
