[package]
name = "graph_rdfa_processor"
version = "0.1.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
lazy_static = "1.4.0"
scraper = "0.18.0"
url = "2.4.1"
uuid = { version = "1.5.0", features = ["v4"] }
