[package]
name = "rdfa-wasm"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true


[lib]
crate-type = ["cdylib"]

[dependencies]
graph-rdfa-processor.workspace = true
wasm-bindgen.workspace = true
