name: Release Github Pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - name: Build
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build --target web --release --scope nbittich ./rdfa-wasm
          mkdir ghPages
          cp -r  ./rdfa-wasm/pkg ghPages
          cp ./rdfa-wasm/app.js ghPages
          cp ./rdfa-wasm/style.css ghPages
          cp ./rdfa-wasm/favicon.ico ghPages
          cp ./rdfa-wasm/index.html ghPages
      - name: Upload ghPages
        uses: actions/upload-artifact@v4
        with:
          name: ghPages
          path: ghPages
  gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download ghPages
        uses: actions/download-artifact@v4
        with:
          name: ghPages
          path: "_site/"
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
      - name: Deploy pages
        uses: actions/deploy-pages@v4
